# 4. Fetching webpage with `Requests`

- URL: `https://www.bbc.com/sport/football/premier-league/top-scorers`

In [4]:
# import libraries

import requests
from bs4 import BeautifulSoup

In [5]:
# Get request

url = "https://www.bbc.com/sport/football/premier-league/top-scorers"

response = requests.get(url)

In [6]:
# check for errors

response.raise_for_status()

In [7]:
print(response.raise_for_status())

None

In [8]:
# status code 

response.status_code

200

In [9]:
# text (string format)

response.text[:200]

'<!DOCTYPE html><html lang="en-GB" class="no-js"><head><meta charSet="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title data-rh="true">Premier League Top Scorers - B'

In [10]:
type(response.text)

str

In [11]:
# content (binary format)

response.content[:200]

b'<!DOCTYPE html><html lang="en-GB" class="no-js"><head><meta charSet="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title data-rh="true">Premier League Top Scorers - B'

In [12]:
type(response.content)

bytes

- can use either `content` or `text` attribute to create the soup object
- with `text`, we must be certain about the encoding
- with `content`, we let Beautiful Soup handle the encoding mostly

In [13]:
# soup object

soup = BeautifulSoup(response.content, "html.parser")

In [14]:
print(soup.prettify())

<!DOCTYPE html>
<html class="no-js" lang="en-GB">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title data-rh="true">
   Premier League Top Scorers - BBC Sport
  </title>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" name="description"/>
  <meta content="#FFFFFF" data-rh="true" name="theme-color"/>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" property="og:description"/>
  <meta content="https://static.files.bbci.co.uk/core/website/assets/static/sport/bbc-sport-logo.ebbfcde41a.webp" data-rh="true" property="og:image"/>
  <meta content="BBC Sport" data-rh="true" property="og:site_name"/>
  <meta content="Premier League Top Scorers - BBC Sport" data-rh="true" property="og:title"/>
  <meta content="article" data-rh="true" property="og:type"/>
  <meta content="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" data-rh="true" property="og:url"/>
  <meta content="summary" data-rh="true" name="twitter:card"/>
  <meta content="@BBCSport" data-rh="true" name="twitter:creator"/>
  <meta content="@BBCSport" data-rh="true" name="twitter:site"/>
  <meta content="Premier League Top Scorers - BBC Sport" data-rh="true" name="twitter:title"/>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" name="twitter:description"/>
  <meta content="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" data-rh="true" name="twitter:url"/>
  <meta content="https://static.files.bbci.co.uk/core/website/assets/static/icons/windows-phone/sport/windows-phone-icon-270x270.3e5b0f9ac9.png" data-rh="true" name="msapplication-TileImage" type="metaTags"/>
  <meta content="telephone=no" data-rh="true" name="format-detection"/>
  <meta content="max-image-preview:large" data-rh="true" name="robots"/>
  <link data-rh="true" href="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" rel="canonical"/>
  <link data-rh="true" href="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" hreflang="en-gb" rel="alternate"/>
  <link data-rh="true" href="https://www.bbc.com/sport/football/premier-league/top-scorers" hreflang="en" rel="alternate"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-36.4462ac53e0.png" rel="icon" sizes="36x36" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-48.889764e1f5.png" rel="icon" sizes="48x48" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-57.d66bb4d3af.png" rel="icon" sizes="57x57" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-60.ea49e5ffb8.png" rel="icon" sizes="60x60" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-72.1e5fc819b5.png" rel="icon" sizes="72x72" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-76.34703514a6.png" rel="icon" sizes="76x76" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-96.a040328c4e.png" rel="icon" sizes="96x96" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-114.fe9c3f2019.png" rel="icon" sizes="114x114" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-120.8ed642b324.png" rel="icon" sizes="120x120" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-128.120915c059.png" rel="icon" sizes="128x128" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-144.15dd10e42c.png" rel="icon" sizes="144x144" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-152.fd46d402eb.png" rel="icon" sizes="152x152" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-180.f21cfb03df.png" rel="icon" sizes="180x180" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-192.79e4069625.png" rel="icon" sizes="192x192" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-384.ae211a8aa4.png" rel="icon" sizes="384x384" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-512.239d26b83e.png" rel="icon" sizes="512x512" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/favicon/sport/favicon-16.ffa949edba.png" rel="icon" sizes="16x16" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/favicon/sport/favicon-32.729e81a820.png" rel="icon" sizes="32x32" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/manifest.1ccdbcfd4cc3bf889128a50903c2b22c81758637.json" rel="manifest"/>
  <script nonce="cx7veQAaHd3tKoNXDul6+5XRF2Iasg0McIkKBsDCyo7symzqFE">
   document.querySelector("html").classList.remove("no-js")
  </script>
  <style data-emotion="ssrcss-global 19mm8ji">
   html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,main,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section{display:block;}:root{interpolate-size:allow-keywords;}body{line-height:1;-webkit-text-size-adjust:none;-moz-text-size-adjust:none;-ms-text-size-adjust:none;text-size-adjust:none;}ol,ul{list-style:none;}blockquote,q{quotes:none;}blockquote::before,blockquote::after,q::before,q::after{content:'';content:none;}table{border-collapse:collapse;border-spacing:0;}button{-webkit-appearance:none;-moz-appearance:none;-ms-appearance:none;appearance:none;margin:0;padding:0;background:none;border-radius:0;border:0;font-family:inherit;color:inherit;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Rg.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Rg.woff) format('woff');font-display:swap;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_It.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_It.woff) format('woff');font-display:swap;font-style:italic;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_BdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_BdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:700;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Lt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Lt.woff) format('woff');font-display:swap;font-weight:300;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_LtIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_LtIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:300;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:800;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Md.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Md.woff) format('woff');font-display:swap;font-weight:500;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_MdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_MdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:500;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Rg.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Rg.woff) format('woff');font-display:swap;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_It.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_It.woff) format('woff');font-display:swap;font-style:italic;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_BdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_BdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:700;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Lt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Lt.woff) format('woff');font-display:swap;font-weight:300;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_LtIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_LtIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:300;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:800;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Md.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Md.woff) format('woff');font-display:swap;font-weight:500;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_MdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_MdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:500;}@font-face{font-family:'ReithRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSemiRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSemiRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}body{background-color:#FFFFFF;}:focus-visible{box-shadow:0 0 0 0.125rem #FFFFFF;outline:0.125rem solid #000000;outline-offset:0.125rem;}
  </style>
  <style data-emotion="ssrcss 181c4hk-SectionWrapper 1imfos9-PageStack 15ehc5c-GlobalNavigation 1xvly21-Wrap 1bvvlvf-GlobalNavigationContent gzqup8-GlobalNavigationItem jlhv6f-NavigationLink-LogoLink 13kjque-LogoIconWrapper i2z2ig-VisuallyHidden 49m975-AccessibilityLinksOffset b9gyag-AccessibilityLink sqg48l-GlobalNavigationItem k58ud3-AccountOptionsList 1t7ltsf-GlobalNavigationProduct-GlobalNavigationAccount 5fw2ee-AccountComponentWrapper uwr32o-StyledAccountPlaceholderComponent n7m3zs-StyledLoadingPlaceholderWrapper 9fdrh7-StyledAccountPlaceholderIconWrapper pi49ph-Skeleton-StyledAccountPlaceholderIcon h42kmd-StyledLoadingPlaceHolderTextWrapper 31p6q0-Skeleton-StyledLoadingPlaceHolderText dhpui-NavigationLink-AccountLink 1oeiyy4-ForYouIconWrapper xi5oyi-StyledIcon 1kiv1pn-AccountText 13wl9em-VerticalSeparator 1mb3gpt-GlobalNavigationBarLinkList 1bwqj1o-GlobalNavigationProduct 162wxwt-NavigationLink en6he4-NavItemHoverState umlvt2-NavigationLink-MenuToggleControlLink cuok5u-NavItemHoverState 13dpa8i-DotsMenuIconWrapper 1naw1ix-LastGlobalNavigationItem 1sakhrp-GlobalNavigationItem-GlobalNavigationBurger 1myt22i-BurgerMenuIconWrapper cl7jld-GlobalNavigationItem 18ahbb2-NavigationLink-SearchLink 1lc3dkf-IconWrapper-SearchIconWrapper v56yg5-SearchText hi2bgt-GlobalNavigationDrawer 1sdh8fh-GlobalNavigationMoreMenu 1obp207-MenuWrapper 1xli83y-MenuLinkList 1cnl2eg-MenuLinkListItem kffy1u-MenuLink h8eoet-CloseButtonWrapper 1qzzpqq-CallToActionLink 1hfawy1-IconWrapper t8w0yc-ProductNavigationContainer 6c9k91-Masthead 12x0ma7-ContentWrapper 1nqrevo-LogoWrapper 1vyfvn-LogoLink 1xljs8d-LogoIcon gmdx8l-Navigation ehbb92-MainNavBarContainer 1iqquil-MenuContainer-PrimaryNavBarContainer 15o6r8s-PrimaryListContainer 1cjxixv-ToggleContainer rcbzzj-StyledToggle uq8y1d-IconWrapper hlliht-MenuListContainer jdnupy-StyledMenuList 42zvi3-StyledMenuItem yt6oi0-StyledLink 1sdg3ez-LinkTextContainer 1fbvkm-StyledLink 1ro2vxk-ToggleContainer dr47hj-MenuContainer-MoreMenuWrapper wdgq9j-MoreMenuListContainer j6f6xh-MenuListContainer 1mlqmic-ListTitle 65sh09-StyledMenuList 1cp5r2l-StyledMenuItem 1iyklul-StyledLink i9csl0-LinkTextContainer s6ioaa-MenuContainer-SecondaryNavBarContainer 1qa7b1l-MenuListContainer t9pxd6-StyledMenuList 1k13if-StyledMenuItem 1lwb8hg-StyledLink 12rp8ws-LinkTextContainer p4fm83-IconContainer 1p1be2q-StyledLink t9s73x-StandardZone gqrsw0-Wrapper 1qdh4qq-HeadingWrapper 1fbl9fk-Heading 59a716-SearchWrapper 1hy9pi-StyledComboboxWrapper 11raoza-StyledWrapper 2j3s5k-SearchBarWrapper 1ygb9tb-StyledDiv 15ptkq8-FocusDiv zbw5ic-IconWrapper bv7dy7-StyledInput 1ps7ft7-StyledFormWrapper 1s5xenc-Button alld1g-Tabs nzlsna-TabListContainer f5gts8-TabList ii4qg7-TabListItem 1dci2zz-TabLink 1jv6l5n-TabPanelContainer 198yp8f-TableWrapper 140ec4w-RelativeWrapper 1dv84pz-OuterTableWrapper 1pwsb40-TableWrapper 1jqazkt-TableHead 5zeqs7-StyledTableHeading 1kfc4np-StyledTableHeading 1mdwl7u-StyledTableHeading v6lph0-StyledTableHeading tgicz1-StyledTableHeading 1irbcwd-StyledTableHeading hpa5ss-TableRowBody 63h33v-StyledTableData 19jmwd7-CellWrapper wjp01q-RankAndBadgeWrapper 1xljqjf-Rank pp8itw-BadgeWrapper bdya4g-MobileOnlyWrapper 1ij97kg-BadgeContainer 1knyx38-BadgeImage dngukv-DesktopOnlyWrapper 1b9x5pa-BadgeContainer 1rqvnx-PlayerName cfavl3-TeamsSummary 80pxhl-StyledTableData 1fyor78-CellWrapper 1y8qrt1-StyledTableData ero735-CellWrapper swlzru-StyledTableData 1f02lw1-StyledTableData 1aeslnf-StyledTableData kwa1w9-GlobalFooterStyling vohj05-Stack 1010d8g-Columns 14s3o7n-Link-NavigationLink 15twdc6-Stack 17ehax8-Cluster rf8ukd-ClusterItems z6a8o1-Link-LegalLink 1q0x1qg-Paragraph 1rt7jfo-Link">

# 5. HTML parsing with `Beautiful Soup`: A Mini Project

- scrape data from a public website
- organize the data as a dataframe
- export the data as an excel sheet

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

C:\Users\ANANTH\anaconda3\envs\web_scraping\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [2]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    print("Successful!")

Successful!

In [3]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    print("Successful!")
    print(soup.prettify())

Successful!
<!DOCTYPE html>
<html class="no-js" lang="en-GB">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title data-rh="true">
   Premier League Top Scorers - BBC Sport
  </title>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" name="description"/>
  <meta content="#FFFFFF" data-rh="true" name="theme-color"/>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" property="og:description"/>
  <meta content="https://static.files.bbci.co.uk/core/website/assets/static/sport/bbc-sport-logo.ebbfcde41a.webp" data-rh="true" property="og:image"/>
  <meta content="BBC Sport" data-rh="true" property="og:site_name"/>
  <meta content="Premier League Top Scorers - BBC Sport" data-rh="true" property="og:title"/>
  <meta content="article" data-rh="true" property="og:type"/>
  <meta content="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" data-rh="true" property="og:url"/>
  <meta content="summary" data-rh="true" name="twitter:card"/>
  <meta content="@BBCSport" data-rh="true" name="twitter:creator"/>
  <meta content="@BBCSport" data-rh="true" name="twitter:site"/>
  <meta content="Premier League Top Scorers - BBC Sport" data-rh="true" name="twitter:title"/>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" name="twitter:description"/>
  <meta content="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" data-rh="true" name="twitter:url"/>
  <meta content="https://static.files.bbci.co.uk/core/website/assets/static/icons/windows-phone/sport/windows-phone-icon-270x270.3e5b0f9ac9.png" data-rh="true" name="msapplication-TileImage" type="metaTags"/>
  <meta content="telephone=no" data-rh="true" name="format-detection"/>
  <meta content="max-image-preview:large" data-rh="true" name="robots"/>
  <link data-rh="true" href="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" rel="canonical"/>
  <link data-rh="true" href="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" hreflang="en-gb" rel="alternate"/>
  <link data-rh="true" href="https://www.bbc.com/sport/football/premier-league/top-scorers" hreflang="en" rel="alternate"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-36.4462ac53e0.png" rel="icon" sizes="36x36" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-48.889764e1f5.png" rel="icon" sizes="48x48" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-57.d66bb4d3af.png" rel="icon" sizes="57x57" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-60.ea49e5ffb8.png" rel="icon" sizes="60x60" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-72.1e5fc819b5.png" rel="icon" sizes="72x72" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-76.34703514a6.png" rel="icon" sizes="76x76" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-96.a040328c4e.png" rel="icon" sizes="96x96" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-114.fe9c3f2019.png" rel="icon" sizes="114x114" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-120.8ed642b324.png" rel="icon" sizes="120x120" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-128.120915c059.png" rel="icon" sizes="128x128" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-144.15dd10e42c.png" rel="icon" sizes="144x144" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-152.fd46d402eb.png" rel="icon" sizes="152x152" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-180.f21cfb03df.png" rel="icon" sizes="180x180" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-192.79e4069625.png" rel="icon" sizes="192x192" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-384.ae211a8aa4.png" rel="icon" sizes="384x384" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-512.239d26b83e.png" rel="icon" sizes="512x512" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/favicon/sport/favicon-16.ffa949edba.png" rel="icon" sizes="16x16" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/favicon/sport/favicon-32.729e81a820.png" rel="icon" sizes="32x32" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/manifest.1ccdbcfd4cc3bf889128a50903c2b22c81758637.json" rel="manifest"/>
  <script nonce="roMF1KUIz2wk3jt2QRDAdyW7LML0w2v2TF3wing8NYjjiaWiOv">
   document.querySelector("html").classList.remove("no-js")
  </script>
  <style data-emotion="ssrcss-global 19mm8ji">
   html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,main,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section{display:block;}:root{interpolate-size:allow-keywords;}body{line-height:1;-webkit-text-size-adjust:none;-moz-text-size-adjust:none;-ms-text-size-adjust:none;text-size-adjust:none;}ol,ul{list-style:none;}blockquote,q{quotes:none;}blockquote::before,blockquote::after,q::before,q::after{content:'';content:none;}table{border-collapse:collapse;border-spacing:0;}button{-webkit-appearance:none;-moz-appearance:none;-ms-appearance:none;appearance:none;margin:0;padding:0;background:none;border-radius:0;border:0;font-family:inherit;color:inherit;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Rg.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Rg.woff) format('woff');font-display:swap;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_It.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_It.woff) format('woff');font-display:swap;font-style:italic;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_BdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_BdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:700;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Lt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Lt.woff) format('woff');font-display:swap;font-weight:300;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_LtIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_LtIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:300;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:800;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Md.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Md.woff) format('woff');font-display:swap;font-weight:500;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_MdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_MdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:500;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Rg.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Rg.woff) format('woff');font-display:swap;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_It.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_It.woff) format('woff');font-display:swap;font-style:italic;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_BdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_BdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:700;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Lt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Lt.woff) format('woff');font-display:swap;font-weight:300;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_LtIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_LtIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:300;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:800;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Md.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Md.woff) format('woff');font-display:swap;font-weight:500;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_MdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_MdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:500;}@font-face{font-family:'ReithRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSemiRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSemiRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}body{background-color:#FFFFFF;}:focus-visible{box-shadow:0 0 0 0.125rem #FFFFFF;outline:0.125rem solid #000000;outline-offset:0.125rem;}
  </style>
  <style data-emotion="ssrcss 181c4hk-SectionWrapper 1imfos9-PageStack 15ehc5c-GlobalNavigation 1xvly21-Wrap 1bvvlvf-GlobalNavigationContent gzqup8-GlobalNavigationItem jlhv6f-NavigationLink-LogoLink 13kjque-LogoIconWrapper i2z2ig-VisuallyHidden 49m975-AccessibilityLinksOffset b9gyag-AccessibilityLink sqg48l-GlobalNavigationItem k58ud3-AccountOptionsList 1t7ltsf-GlobalNavigationProduct-GlobalNavigationAccount 5fw2ee-AccountComponentWrapper uwr32o-StyledAccountPlaceholderComponent n7m3zs-StyledLoadingPlaceholderWrapper 9fdrh7-StyledAccountPlaceholderIconWrapper pi49ph-Skeleton-StyledAccountPlaceholderIcon h42kmd-StyledLoadingPlaceHolderTextWrapper 31p6q0-Skeleton-StyledLoadingPlaceHolderText dhpui-NavigationLink-AccountLink 1oeiyy4-ForYouIconWrapper xi5oyi-StyledIcon 1kiv1pn-AccountText 13wl9em-VerticalSeparator 1mb3gpt-GlobalNavigationBarLinkList 1bwqj1o-GlobalNavigationProduct 162wxwt-NavigationLink en6he4-NavItemHoverState umlvt2-NavigationLink-MenuToggleControlLink cuok5u-NavItemHoverState 13dpa8i-DotsMenuIconWrapper 1naw1ix-LastGlobalNavigationItem 1sakhrp-GlobalNavigationItem-GlobalNavigationBurger 1myt22i-BurgerMenuIconWrapper cl7jld-GlobalNavigationItem 18ahbb2-NavigationLink-SearchLink 1lc3dkf-IconWrapper-SearchIconWrapper v56yg5-SearchText hi2bgt-GlobalNavigationDrawer 1sdh8fh-GlobalNavigationMoreMenu 1obp207-MenuWrapper 1xli83y-MenuLinkList 1cnl2eg-MenuLinkListItem kffy1u-MenuLink h8eoet-CloseButtonWrapper 1qzzpqq-CallToActionLink 1hfawy1-IconWrapper t8w0yc-ProductNavigationContainer 6c9k91-Masthead 12x0ma7-ContentWrapper 1nqrevo-LogoWrapper 1vyfvn-LogoLink 1xljs8d-LogoIcon gmdx8l-Navigation ehbb92-MainNavBarContainer 1iqquil-MenuContainer-PrimaryNavBarContainer 15o6r8s-PrimaryListContainer 1cjxixv-ToggleContainer rcbzzj-StyledToggle uq8y1d-IconWrapper hlliht-MenuListContainer jdnupy-StyledMenuList 42zvi3-StyledMenuItem yt6oi0-StyledLink 1sdg3ez-LinkTextContainer 1fbvkm-StyledLink 1ro2vxk-ToggleContainer dr47hj-MenuContainer-MoreMenuWrapper wdgq9j-MoreMenuListContainer j6f6xh-MenuListContainer 1mlqmic-ListTitle 65sh09-StyledMenuList 1cp5r2l-StyledMenuItem 1iyklul-StyledLink i9csl0-LinkTextContainer s6ioaa-MenuContainer-SecondaryNavBarContainer 1qa7b1l-MenuListContainer t9pxd6-StyledMenuList 1k13if-StyledMenuItem 1lwb8hg-StyledLink 12rp8ws-LinkTextContainer p4fm83-IconContainer 1p1be2q-StyledLink t9s73x-StandardZone gqrsw0-Wrapper 1qdh4qq-HeadingWrapper 1fbl9fk-Heading 59a716-SearchWrapper 1hy9pi-StyledComboboxWrapper 11raoza-StyledWrapper 2j3s5k-SearchBarWrapper 1ygb9tb-StyledDiv 15ptkq8-FocusDiv zbw5ic-IconWrapper bv7dy7-StyledInput 1ps7ft7-StyledFormWrapper 1s5xenc-Button alld1g-Tabs nzlsna-TabListContainer f5gts8-TabList ii4qg7-TabListItem 1dci2zz-TabLink 1jv6l5n-TabPanelContainer 198yp8f-TableWrapper 140ec4w-RelativeWrapper 1dv84pz-OuterTableWrapper 1pwsb40-TableWrapper 1jqazkt-TableHead 5zeqs7-StyledTableHeading 1kfc4np-StyledTableHeading 1mdwl7u-StyledTableHeading v6lph0-StyledTableHeading tgicz1-StyledTableHeading 1irbcwd-StyledTableHeading hpa5ss-TableRowBody 63h33v-StyledTableData 19jmwd7-CellWrapper wjp01q-RankAndBadgeWrapper 1xljqjf-Rank pp8itw-BadgeWrapper bdya4g-MobileOnlyWrapper 1ij97kg-BadgeContainer 1knyx38-BadgeImage dngukv-DesktopOnlyWrapper 1b9x5pa-BadgeContainer 1rqvnx-PlayerName cfavl3-TeamsSummary 80pxhl-StyledTableData 1fyor78-CellWrapper 1y8qrt1-StyledTableData ero735-CellWrapper swlzru-StyledTableData 1f02lw1-StyledTableData 1aeslnf-StyledTableData kwa1w9-GlobalFooterStyling vohj05-Stack 1010d8g-Columns 14s3o7n-Link-NavigationLink 15twdc6-Stack 17ehax8-Cluster rf8ukd-ClusterItems z6a8o1-Link-LegalLink 1q0x1qg-Paragraph 1rt7jfo-Link">

In [4]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    print(len(soup.find_all("tbody")))
    print(soup.find_all("tbody"))

2

In [5]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    print(len(soup.find("tbody").find_all("tr", class_="ssrcss-hpa5ss-TableRowBody e1icz100")))
    print(soup.find("tbody").find_all("tr", class_="ssrcss-hpa5ss-TableRowBody e1icz100"))

29

In [6]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_="ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        print(player)
        break

<tr class="ssrcss-hpa5ss-TableRowBody e1icz100"><td class="ssrcss-63h33v-StyledTableData ef9ipf1"><div class="ssrcss-19jmwd7-CellWrapper ef9ipf0" value="1"><div class="ssrcss-wjp01q-RankAndBadgeWrapper e1n6h4mf2"><span class="ssrcss-1xljqjf-Rank e1n6h4mf1">1</span><div class="ssrcss-pp8itw-BadgeWrapper e1n6h4mf0"><div class="ssrcss-bdya4g-MobileOnlyWrapper e1v3gc7i1"><div class="ssrcss-1ij97kg-BadgeContainer ezmsq4q1" data-testid="badge-container-manchester-city" size="20"><img alt="" aria-hidden="true" class="ssrcss-1knyx38-BadgeImage ezmsq4q0" data-testid="badge-img-manchester-city" src="https://static.files.bbci.co.uk/core/website/assets/static/sport/football/manchester-city.e4f9593ae9.svg"/></div></div><div class="ssrcss-dngukv-DesktopOnlyWrapper e1v3gc7i0"><div class="ssrcss-1b9x5pa-BadgeContainer ezmsq4q1" data-testid="badge-container-manchester-city" size="24"><img alt="" aria-hidden="true" class="ssrcss-1knyx38-BadgeImage ezmsq4q0" data-testid="badge-img-manchester-city" src="https://static.files.bbci.co.uk/core/website/assets/static/sport/football/manchester-city.e4f9593ae9.svg"/></div></div></div></div></div></td><td class="ssrcss-63h33v-StyledTableData ef9ipf1"><div class="ssrcss-19jmwd7-CellWrapper ef9ipf0"><div data-player-id="urn:bbc:sportsdata:football:player:s-atzboo800gv7gic2rgvgo0kq1" data-team-id="urn:bbc:sportsdata:football:team:manchester-city"></div><div class="ssrcss-dngukv-DesktopOnlyWrapper e1v3gc7i0"><div role="text"><div class="ssrcss-1rqvnx-PlayerName e1n8xy5b1">E. Haaland</div><div class="ssrcss-cfavl3-TeamsSummary e1n8xy5b0">Man City</div></div></div><div class="ssrcss-bdya4g-MobileOnlyWrapper e1v3gc7i1"><div role="text"><div class="ssrcss-1rqvnx-PlayerName e1n8xy5b1">E. Haaland</div><div class="ssrcss-cfavl3-TeamsSummary e1n8xy5b0">Man City</div></div></div></div></td><td class="ssrcss-80pxhl-StyledTableData ef9ipf1"><div class="ssrcss-1fyor78-CellWrapper ef9ipf0" value="22">22</div></td><td class="ssrcss-1y8qrt1-StyledTableData ef9ipf1"><div class="ssrcss-1fyor78-CellWrapper ef9ipf0" value="22">22</div></td><td class="ssrcss-80pxhl-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="7">7</div></td><td class="ssrcss-1y8qrt1-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="7">7</div></td><td class="ssrcss-80pxhl-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="28">28</div></td><td class="ssrcss-1y8qrt1-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="28">28</div></td><td class="ssrcss-80pxhl-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="0.85">0.85</div></td><td class="ssrcss-swlzru-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="106">106</div></td><td class="ssrcss-1f02lw1-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="106">106</div></td><td class="ssrcss-1aeslnf-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="98">98</div></td><td class="ssrcss-80pxhl-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="22%">22%</div></td><td class="ssrcss-1aeslnf-StyledTableData ef9ipf1"><div class="ssrcss-ero735-CellWrapper ef9ipf0" value="49%">49%</div></td></tr>

In [7]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_="ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        print(player.find("div", class_="ssrcss-1rqvnx-PlayerName e1n8xy5b1"))
        break

<div class="ssrcss-1rqvnx-PlayerName e1n8xy5b1">E. Haaland</div>

In [8]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_="ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        print(player.find("div", class_="ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True))
        break

E. Haaland

In [9]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_="ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        print(player.find("div", class_="ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True))
        # break

E. Haaland
Igor Thiago
A. Semenyo
João Pedro
H. Ekitiké
D. Calvert-Lewin
D. Welbeck
V. Gyökeres
H. Wilson
Bruno Guimarães
B. Mbeumo
C. Palmer
M. Rogers
J. Bowen
Richarlison
R. Jiménez
E. Fernández
M. Gibbs-White
B. Šeško
O. Watkins
J. Kroupi
J. Mateta
Bruno Fernandes
P. Foden
K. Schade
N. Woltemade
I. Sarr
J. Anthony
Z. Flemming

In [10]:
player_names = []

In [11]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_="ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        player_name = player.find("div", class_="ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        player_names.append(player_name)
        # break

In [12]:
print(player_names)

['E. Haaland', 'Igor Thiago', 'A. Semenyo', 'João Pedro', 'H. Ekitiké', 'D. Calvert-Lewin', 'D. Welbeck', 'V. Gyökeres', 'H. Wilson', 'Bruno Guimarães', 'B. Mbeumo', 'C. Palmer', 'M. Rogers', 'J. Bowen', 'Richarlison', 'R. Jiménez', 'E. Fernández', 'M. Gibbs-White', 'B. Šeško', 'O. Watkins', 'J. Kroupi', 'J. Mateta', 'Bruno Fernandes', 'P. Foden', 'K. Schade', 'N. Woltemade', 'I. Sarr', 'J. Anthony', 'Z. Flemming']

In [13]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        player_name = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        print(player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0"))
        break

<div class="ssrcss-cfavl3-TeamsSummary e1n8xy5b0">Man City</div>

In [14]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        print(player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True))

Man City
Brentford
Man City
Chelsea
Liverpool
Leeds
Brighton
Arsenal
Fulham
Newcastle
Man Utd
Chelsea
Aston Villa
West Ham
Spurs
Fulham
Chelsea
Nottm Forest
Man Utd
Aston Villa
Bournemouth
Crystal Palace
Man Utd
Man City
Brentford
Newcastle
Crystal Palace
Burnley
Burnley

In [15]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        # team_name   = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        # player_names.append(player_name)
        # team_names.append(team_name)
        print(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0"))
        break

<div class="ssrcss-1fyor78-CellWrapper ef9ipf0" value="22">22</div>

In [16]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        # team_name   = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        # player_names.append(player_name)
        # team_names.append(team_name)
        print(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        print(type(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True)))
        break

22
<class 'str'>

In [20]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name  = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        # team_name    = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        # goals_scored = int(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        # player_names.append(player_name)
        # team_names.append(team_name)
        # goals.append(goals_scored)

        # assisted value
        print(player.find("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0"))
        print(type(player.find("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0").get_text(strip = True)))
        break

<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="7">7</div>
<class 'str'>

In [22]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name  = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        # team_name    = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        # goals_scored = int(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        # player_names.append(player_name)
        # team_names.append(team_name)
        # goals.append(goals_scored)

        # played value
        print(player.find("div",class_ = "ssrcss-ero735-CellWrapper ef9ipf0"))
        print(type(player.find("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0").get_text(strip = True)))
        break

<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="7">7</div>
<class 'str'>

- the attributes `assists` and `played` had the same classid  `ssrcss-ero735-CellWrapper ef9ipf0`

In [25]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name  = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        # team_name    = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        # goals_scored = int(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        # player_names.append(player_name)
        # team_names.append(team_name)
        # goals.append(goals_scored)

        # played value
        print(player.find_all("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0"))
        print(len(player.find_all("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0")))
        break

[<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="7">7</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="7">7</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="28">28</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="28">28</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="0.85">0.85</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="106">106</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="106">106</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="98">98</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="22%">22%</div>, <div class="ssrcss-ero735-CellWrapper ef9ipf0" value="49%">49%</div>]
10

In [27]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name  = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        # team_name    = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        # goals_scored = int(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        # player_names.append(player_name)
        # team_names.append(team_name)
        # goals.append(goals_scored)

        # played value
        for div_tag in player.find_all("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0"):
            print(div_tag)
        break

<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="7">7</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="7">7</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="28">28</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="28">28</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="0.85">0.85</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="106">106</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="106">106</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="98">98</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="22%">22%</div>
<div class="ssrcss-ero735-CellWrapper ef9ipf0" value="49%">49%</div>

In [31]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name  = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        # team_name    = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        # goals_scored = int(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        stats = player.find_all("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0")
        assists_made = stats[0]
        matches_played = stats[2]
        shots_taken = stats[-3]

        print(f"assists_made   : {type(assists_made)}")
        print(f"matches_played : {type(matches_played)}")
        print(f"shots_taken    : {type(shots_taken)}")

        # player_names.append(player_name)
        # team_names.append(team_name)
        # goals.append(goals_scored)
        break

assists_made   : <class 'bs4.element.Tag'>
matches_played : <class 'bs4.element.Tag'>
shots_taken    : <class 'bs4.element.Tag'>

In [32]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        # player_name  = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        # team_name    = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        # goals_scored = int(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        stats = player.find_all("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0")
        assists_made = stats[0].get_text(strip = True)
        matches_played = stats[2].get_text(strip = True)
        shots_taken = stats[-3].get_text(strip = True)

        print(f"assists_made   : {assists_made} {type(assists_made)}")
        print(f"matches_played : {matches_played} {type(matches_played)}")
        print(f"shots_taken    : {shots_taken} {type(shots_taken)}")

        # player_names.append(player_name)
        # team_names.append(team_name)
        # goals.append(goals_scored)
        break

assists_made   : 7 <class 'str'>
matches_played : 28 <class 'str'>
shots_taken    : 98 <class 'str'>

In [33]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:
        player_name  = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        team_name    = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        goals_scored = int(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        stats = player.find_all("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0")
        assists_made = int(stats[0].get_text(strip = True))
        matches_played = int(stats[2].get_text(strip = True))
        shots_taken = int(stats[-3].get_text(strip = True))
        print(assists_made, matches_played, shots_taken)


        # player_names.append(player_name)
        # team_names.append(team_name)
        # goals.append(goals_scored)

7 28 98
1 29 67
4 28 67
5 29 57
4 26 63
1 26 54
0 28 38
0 28 42
6 27 58
4 23 32
3 24 57
1 18 41
5 29 66
5 29 65
3 24 39
3 28 62
3 28 55
2 29 63
1 24 51
1 28 57
0 24 29
0 23 54
14 26 64
3 25 51
3 26 44
2 25 30
1 19 34
1 28 38
0 20 31

In [2]:
player_names = []
team_names = []
goals = []
assists = []
num_matches = []
shots = []

In [3]:
try:
    url = "https://www.bbc.com/sport/football/premier-league/top-scorers"
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, "html.parser")
    players = soup.find("tbody").find_all("tr", class_ = "ssrcss-hpa5ss-TableRowBody e1icz100")
    for player in players:

        # extract the attribute values
        player_name  = player.find("div", class_ = "ssrcss-1rqvnx-PlayerName e1n8xy5b1").get_text(strip = True)
        team_name    = player.find("div", class_ = "ssrcss-cfavl3-TeamsSummary e1n8xy5b0").get_text(strip = True)
        goals_scored = int(player.find("div", class_="ssrcss-1fyor78-CellWrapper ef9ipf0").get_text(strip = True))
        stats = player.find_all("div", class_ = "ssrcss-ero735-CellWrapper ef9ipf0")
        assists_made = int(stats[0].get_text(strip = True))
        matches_played = int(stats[2].get_text(strip = True))
        shots_taken = int(stats[-3].get_text(strip = True))

        # store the attribute values into lists
        player_names.append(player_name)
        team_names.append(team_name)
        goals.append(goals_scored)
        assists.append(assists_made)
        num_matches.append(matches_played)
        shots.append(shots_taken)

    # create a dictionary
    data = {
        "players": player_names,
        "teams": team_names,
        "goals": goals,
        "assists": assists,
        "matches": num_matches,
        "shots": shots
    }
    
    # create a dataframe
    df_players = pd.DataFrame(data)

In [4]:
df_players

             players           teams  goals  assists  matches  shots
0         E. Haaland        Man City     22        7       28     98
1        Igor Thiago       Brentford     18        1       29     67
2         A. Semenyo        Man City     15        4       28     67
3         João Pedro         Chelsea     14        5       29     57
4         H. Ekitiké       Liverpool     11        4       26     63
5   D. Calvert-Lewin           Leeds     10        1       26     54
6         D. Welbeck        Brighton     10        0       28     38
7        V. Gyökeres         Arsenal     10        0       28     42
8          H. Wilson          Fulham      9        6       27     58
9    Bruno Guimarães       Newcastle      9        4       23     32
10         B. Mbeumo         Man Utd      9        3       24     57
11         C. Palmer         Chelsea      9        1       18     41
12         M. Rogers     Aston Villa      8        5       29     66
13          J. Bowen        West Ham      8        5       29     65
14       Richarlison           Spurs      8        3       24     39
15        R. Jiménez          Fulham      8        3       28     62
16      E. Fernández         Chelsea      8        3       28     55
17    M. Gibbs-White    Nottm Forest      8        2       29     63
18          B. Šeško         Man Utd      8        1       24     51
19        O. Watkins     Aston Villa      8        1       28     57
20         J. Kroupi     Bournemouth      8        0       24     29
21         J. Mateta  Crystal Palace      8        0       23     54
22   Bruno Fernandes         Man Utd      7       14       26     64
23          P. Foden        Man City      7        3       25     51
24         K. Schade       Brentford      7        3       26     44
25      N. Woltemade       Newcastle      7        2       25     30
26           I. Sarr  Crystal Palace      7        1       19     34
27        J. Anthony         Burnley      7        1       28     38
28       Z. Flemming         Burnley      7        0       20     31

In [5]:
df_players.head()

       players      teams  goals  assists  matches  shots
0   E. Haaland   Man City     22        7       28     98
1  Igor Thiago  Brentford     18        1       29     67
2   A. Semenyo   Man City     15        4       28     67
3   João Pedro    Chelsea     14        5       29     57
4   H. Ekitiké  Liverpool     11        4       26     63

In [6]:
df_players.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   players  29 non-null     str
 1   teams    29 non-null     str
 2   goals    29 non-null     int64
 3   assists  29 non-null     int64
 4   matches  29 non-null     int64
 5   shots    29 non-null     int64
dtypes: int64(4), str(2)
memory usage: 1.5 KB

In [7]:
df_players.describe()

           goals    assists    matches      shots
count  29.000000  29.000000  29.000000  29.000000
mean    9.482759   2.862069  25.827586  51.965517
std     3.531700   2.899805   3.059750  15.319182
min     7.000000   0.000000  18.000000  29.000000
25%     8.000000   1.000000  24.000000  39.000000
50%     8.000000   3.000000  26.000000  54.000000
75%    10.000000   4.000000  28.000000  63.000000
max    22.000000  14.000000  29.000000  98.000000

In [8]:
df_players.to_excel("EPL Top Scorers.xlsx", index = False)