# Import Libraries

In [36]:
import numpy as np
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
import time

In [4]:
driver = webdriver.Chrome()
driver.maximize_window()

url = "https://finance.yahoo.com/"
driver.get(url)

In [27]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

url = "https://finance.yahoo.com/"
driver.get(url)

# wait for webpage to load
# In the lambda function, d is our webdriver instance
page_title = driver.title
try:
    wait.until(
        lambda d: d.execute_script("return document.readyState") == "complete"
    )
except:
    print(f"The page {page_title} didn't fully loaded within the given duration")
else:
    print(f"The page {page_title} is fully loaded")

The page Yahoo Finance - Stock Market Live, Quotes, Business & Finance News is fully loaded

In [28]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait):
    # wait for webpage to load
    # In the lambda function, d is our webdriver instance
    page_title = driver.title
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{page_title}\" didn't fully loaded within the given duration")
    else:
        print(f"The page \"{page_title}\" is fully loaded")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

The page "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News" is fully loaded

In [6]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait):
    # wait for webpage to load
    # In the lambda function, d is our webdriver instance
    page_title = driver.title
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{page_title}\" didn't fully loaded within the given duration")
    else:
        print(f"The page \"{page_title}\" is fully loaded")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

# hovering on market menu
actions = ActionChains(driver)
market_menu = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/a[1]/div[1]"))
)
actions.move_to_element(market_menu).perform()

The page "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News" is fully loaded

In [5]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait):
    # wait for webpage to load
    # In the lambda function, d is our webdriver instance
    page_title = driver.title
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{page_title}\" didn't fully loaded within the given duration\n")
    else:
        print(f"The page \"{page_title}\" is fully loaded\n")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

# hovering on market menu
actions = ActionChains(driver)
market_menu = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/a[1]/div[1]"))
)
actions.move_to_element(market_menu).perform()

# Navigate and locate stocks
stocks_element = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(stocks_element).perform()

most_active = wait.until(
    EC.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(most_active).perform()
most_active.click()

wait_for_page_to_load(driver, wait)

print(driver.current_url)

The page "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News" is fully loaded

The page "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News" is fully loaded

https://finance.yahoo.com/

In [8]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait, old_url=None):
    """
    Waits for the URL to change (if old_url is provided) and then 
    waits for the document.readyState to be complete.
    """
    # 1. If we are coming from another page, wait for the URL to actually change first
    if old_url:
        try:
            wait.until(EC.url_changes(old_url))
        except:
            print("The URL did not change within the timeout period.")

    # 2. Now wait for the new page to report 'complete' status
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{driver.title}\" didn't fully load within the duration\n")
    else:
        # After the wait, driver.title and driver.current_url will be updated
        print(f"Successfully moved to: \"{driver.title}\"")
        print(f"Current URL: {driver.current_url}\n")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

# hovering on market menu
actions = ActionChains(driver)
market_menu = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/a[1]/div[1]"))
)
actions.move_to_element(market_menu).perform()

# Navigate and locate stocks
stocks_element = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(stocks_element).perform()

most_active = wait.until(
    EC.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(most_active).perform()
most_active.click()

# wait_for_page_to_load(driver, wait)

wait_for_page_to_load(driver, wait, old_url = driver.current_url)

Successfully moved to: "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News"
Current URL: https://finance.yahoo.com/

Successfully moved to: "Most Active Stocks: US stocks with the highest trading volume today - Yahoo Finance"
Current URL: https://finance.yahoo.com/markets/stocks/most-active/

# Scraping the Data

In [13]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait, old_url=None):
    """
    Waits for the URL to change (if old_url is provided) and then 
    waits for the document.readyState to be complete.
    """
    # 1. If we are coming from another page, wait for the URL to actually change first
    if old_url:
        try:
            wait.until(EC.url_changes(old_url))
        except:
            print("The URL did not change within the timeout period.")

    # 2. Now wait for the new page to report 'complete' status
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{driver.title}\" didn't fully load within the duration\n")
    else:
        # After the wait, driver.title and driver.current_url will be updated
        print(f"Successfully moved to: \"{driver.title}\"")
        print(f"Current URL: {driver.current_url}\n")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

# hovering on market menu
actions = ActionChains(driver)
market_menu = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/a[1]/div[1]"))
)
actions.move_to_element(market_menu).perform()

# find the stock element and click most_active
stocks_element = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(stocks_element).perform()

most_active = wait.until(
    EC.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(most_active).perform()
most_active.click()

# wait_for_page_to_load(driver, wait)

wait_for_page_to_load(driver, wait, old_url = driver.current_url)

# scraping the data
while True:
    # scraping

    # click next
    try:
        next_button = wait.until(
        EC.element_to_be_clickable((By.XPATH, '//*[@id="main-content-wrapper"]/section[1]/div/div[4]/div[3]/button[3]'))
        )
    except:
        print("The \"next\" button is not clickable. We have navigated through all the pages")
        break
    else:
        next_button.click()
        time.sleep(1)

# close the browser
driver.quit()

Successfully moved to: "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News"
Current URL: https://finance.yahoo.com/

Successfully moved to: "Most Active Stocks: US stocks with the highest trading volume today - Yahoo Finance"
Current URL: https://finance.yahoo.com/markets/stocks/most-active/

The "next" button is not clickable. We have navigated through all the pages

In [14]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait, old_url=None):
    """
    Waits for the URL to change (if old_url is provided) and then 
    waits for the document.readyState to be complete.
    """
    # 1. If we are coming from another page, wait for the URL to actually change first
    if old_url:
        try:
            wait.until(EC.url_changes(old_url))
        except:
            print("The URL did not change within the timeout period.")

    # 2. Now wait for the new page to report 'complete' status
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{driver.title}\" didn't fully load within the duration\n")
    else:
        # After the wait, driver.title and driver.current_url will be updated
        print(f"Successfully moved to: \"{driver.title}\"")
        print(f"Current URL: {driver.current_url}\n")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

# hovering on market menu
actions = ActionChains(driver)
market_menu = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/a[1]/div[1]"))
)
actions.move_to_element(market_menu).perform()

# find the stock element and click most_active
stocks_element = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(stocks_element).perform()

most_active = wait.until(
    EC.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(most_active).perform()
most_active.click()

# wait_for_page_to_load(driver, wait)

wait_for_page_to_load(driver, wait, old_url = driver.current_url)

# scraping the data
while True:
    # scraping
    wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))
    rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    print(len(rows))
    # click next
    try:
        next_button = wait.until(
        EC.element_to_be_clickable((By.XPATH, '//*[@id="main-content-wrapper"]/section[1]/div/div[4]/div[3]/button[3]'))
        )
    except:
        print("The \"next\" button is not clickable. We have navigated through all the pages")
        break
    else:
        next_button.click()
        time.sleep(1)
 
# close the browser
driver.quit()

Successfully moved to: "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News"
Current URL: https://finance.yahoo.com/

Successfully moved to: "Most Active Stocks: US stocks with the highest trading volume today - Yahoo Finance"
Current URL: https://finance.yahoo.com/markets/stocks/most-active/

25
25
21
The "next" button is not clickable. We have navigated through all the pages

In [16]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait, old_url=None):
    """
    Waits for the URL to change (if old_url is provided) and then 
    waits for the document.readyState to be complete.
    """
    # 1. If we are coming from another page, wait for the URL to actually change first
    if old_url:
        try:
            wait.until(EC.url_changes(old_url))
        except:
            print("The URL did not change within the timeout period.")

    # 2. Now wait for the new page to report 'complete' status
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{driver.title}\" didn't fully load within the duration\n")
    else:
        # After the wait, driver.title and driver.current_url will be updated
        print(f"Successfully moved to: \"{driver.title}\"")
        print(f"Current URL: {driver.current_url}\n")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

# hovering on market menu
actions = ActionChains(driver)
market_menu = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/a[1]/div[1]"))
)
actions.move_to_element(market_menu).perform()

# find the stock element and click most_active
stocks_element = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(stocks_element).perform()

most_active = wait.until(
    EC.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(most_active).perform()
most_active.click()

# wait_for_page_to_load(driver, wait)

wait_for_page_to_load(driver, wait, old_url = driver.current_url)

# scraping the data
while True:
    # scraping
    wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))
    rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    print(len(rows))

    for row in rows:
        values = row.find_elements(By.TAG_NAME, "td")
        print([val.text for val in values])
        break
    break
    # click next
    try:
        next_button = wait.until(
        EC.element_to_be_clickable((By.XPATH, '//*[@id="main-content-wrapper"]/section[1]/div/div[4]/div[3]/button[3]'))
        )
    except:
        print("The \"next\" button is not clickable. We have navigated through all the pages")
        break
    else:
        next_button.click()
        time.sleep(1)

# close the browser
driver.quit()

Successfully moved to: "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News"
Current URL: https://finance.yahoo.com/

Successfully moved to: "Most Active Stocks: US stocks with the highest trading volume today - Yahoo Finance"
Current URL: https://finance.yahoo.com/markets/stocks/most-active/

25
['NVDA', 'NVIDIA Corporation', '', '176.56', '-0.83', '-0.47%', '45.287M', '181.124M', '4.291T', '36.20', '+81.68%', '86.62\n212.19']

In [19]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait, old_url=None):
    """
    Waits for the URL to change (if old_url is provided) and then 
    waits for the document.readyState to be complete.
    """
    # 1. If we are coming from another page, wait for the URL to actually change first
    if old_url:
        try:
            wait.until(EC.url_changes(old_url))
        except:
            print("The URL did not change within the timeout period.")

    # 2. Now wait for the new page to report 'complete' status
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{driver.title}\" didn't fully load within the duration\n")
    else:
        # After the wait, driver.title and driver.current_url will be updated
        print(f"Successfully moved to: \"{driver.title}\"")
        print(f"Current URL: {driver.current_url}\n")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

# hovering on market menu
actions = ActionChains(driver)
market_menu = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/a[1]/div[1]"))
)
actions.move_to_element(market_menu).perform()

# find the stock element and click most_active
stocks_element = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(stocks_element).perform()

most_active = wait.until(
    EC.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(most_active).perform()
most_active.click()

# wait_for_page_to_load(driver, wait)

wait_for_page_to_load(driver, wait, old_url = driver.current_url)

data = []
# scraping the data
while True:
    # scraping
    wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))
    rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    print(len(rows))

    for row in rows:
        values = row.find_elements(By.TAG_NAME, "td")
        # print([val.text for val in values])

        stock = {
            "name": values[1].text,
            "symbol": values[0].text,
            "price": values[3].text,
            "change": values[4].text,
            "volume": values[6].text,
            "market_cap": values[8].text,
            "pe_ratio": values[9].text
        }
        data.append(stock)
    break
    # click next
    try:
        next_button = wait.until(
        EC.element_to_be_clickable((By.XPATH, '//*[@id="main-content-wrapper"]/section[1]/div/div[4]/div[3]/button[3]'))
        )
    except:
        print("The \"next\" button is not clickable. We have navigated through all the pages")
        break
    else:
        next_button.click()
        time.sleep(1)

# close the browser
driver.quit()

Successfully moved to: "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News"
Current URL: https://finance.yahoo.com/

Successfully moved to: "Most Active Stocks: US stocks with the highest trading volume today - Yahoo Finance"
Current URL: https://finance.yahoo.com/markets/stocks/most-active/

25

In [20]:
data

[{'name': 'NVIDIA Corporation',
  'symbol': 'NVDA',
  'price': '176.96',
  'change': '-0.43',
  'volume': '49.032M',
  'market_cap': '4.301T',
  'pe_ratio': '36.20'},
 {'name': 'Intel Corporation',
  'symbol': 'INTC',
  'price': '50.46',
  'change': '+0.08',
  'volume': '44.655M',
  'market_cap': '253.36B',
  'pe_ratio': '--'},
 {'name': 'Soleno Therapeutics, Inc.',
  'symbol': 'SLNO',
  'price': '52.20',
  'change': '+12.71',
  'volume': '44.597M',
  'market_cap': '2.804B',
  'pe_ratio': '101.26'},
 {'name': 'Plug Power Inc.',
  'symbol': 'PLUG',
  'price': '2.59',
  'change': '+0.18',
  'volume': '42.008M',
  'market_cap': '3.61B',
  'pe_ratio': '--'},
 {'name': 'Nokia Oyj',
  'symbol': 'NOK',
  'price': '8.99',
  'change': '+0.18',
  'volume': '41.603M',
  'market_cap': '50.215B',
  'pe_ratio': '66.82'},
 {'name': 'Hologic, Inc.',
  'symbol': 'HOLX',
  'price': '76.01',
  'change': '+0.36',
  'volume': '36.38M',
  'market_cap': '16.969B',
  'pe_ratio': '31.48'},
 {'name': 'Tesla, Inc.',
  'symbol': 'TSLA',
  'price': '352.54',
  'change': '-8.05',
  'volume': '29.932M',
  'market_cap': '1.323T',
  'pe_ratio': '333.88'},
 {'name': 'Micron Technology, Inc.',
  'symbol': 'MU',
  'price': '378.82',
  'change': '+12.58',
  'volume': '21.6M',
  'market_cap': '427.208B',
  'pe_ratio': '17.23'},
 {'name': 'Ondas Inc.',
  'symbol': 'ONDS',
  'price': '9.60',
  'change': '0.00',
  'volume': '21.341M',
  'market_cap': '4.625B',
  'pe_ratio': '--'},
 {'name': 'Snap Inc.',
  'symbol': 'SNAP',
  'price': '4.62',
  'change': '-0.01',
  'volume': '20.764M',
  'market_cap': '7.799B',
  'pe_ratio': '--'},
 {'name': 'SoFi Technologies, Inc.',
  'symbol': 'SOFI',
  'price': '16.19',
  'change': '+0.34',
  'volume': '18.698M',
  'market_cap': '20.653B',
  'pe_ratio': '41.10'},
 {'name': 'Netflix, Inc.',
  'symbol': 'NFLX',
  'price': '98.40',
  'change': '-0.26',
  'volume': '18.589M',
  'market_cap': '417.403B',
  'pe_ratio': '39.00'},
 {'name': 'Bitmine Immersion Technologies, Inc.',
  'symbol': 'BMNR',
  'price': '20.65',
  'change': '+1.20',
  'volume': '18.369M',
  'market_cap': '9.403B',
  'pe_ratio': '--'},
 {'name': 'MARA Holdings, Inc.',
  'symbol': 'MARA',
  'price': '8.98',
  'change': '+0.27',
  'volume': '17.462M',
  'market_cap': '3.413B',
  'pe_ratio': '--'},
 {'name': 'Advanced Micro Devices, Inc.',
  'symbol': 'AMD',
  'price': '219.96',
  'change': '+2.46',
  'volume': '17.326M',
  'market_cap': '358.633B',
  'pe_ratio': '83.33'},
 {'name': 'American Airlines Group Inc.',
  'symbol': 'AAL',
  'price': '10.94',
  'change': '+0.10',
  'volume': '14.871M',
  'market_cap': '7.227B',
  'pe_ratio': '64.45'},
 {'name': 'Grab Holdings Limited',
  'symbol': 'GRAB',
  'price': '3.66',
  'change': '+0.05',
  'volume': '14.847M',
  'market_cap': '15.028B',
  'pe_ratio': '60.33'},
 {'name': 'NIO Inc.',
  'symbol': 'NIO',
  'price': '6.33',
  'change': '+0.03',
  'volume': '13.639M',
  'market_cap': '16.006B',
  'pe_ratio': '--'},
 {'name': 'Robinhood Markets, Inc.',
  'symbol': 'HOOD',
  'price': '69.68',
  'change': '+0.78',
  'volume': '13.183M',
  'market_cap': '62.733B',
  'pe_ratio': '33.61'},
 {'name': 'AXT, Inc.',
  'symbol': 'AXTI',
  'price': '44.16',
  'change': '-8.68',
  'volume': '11.714M',
  'market_cap': '2.454B',
  'pe_ratio': '--'},
 {'name': 'Rocket Lab Corporation',
  'symbol': 'RKLB',
  'price': '67.90',
  'change': '+0.17',
  'volume': '11.499M',
  'market_cap': '38.663B',
  'pe_ratio': '--'},
 {'name': 'Apple Inc.',
  'symbol': 'AAPL',
  'price': '259.08',
  'change': '+3.16',
  'volume': '11.314M',
  'market_cap': '3.808T',
  'pe_ratio': '32.46'},
 {'name': 'Denison Mines Corp.',
  'symbol': 'DNN',
  'price': '3.59',
  'change': '-0.08',
  'volume': '11.158M',
  'market_cap': '3.237B',
  'pe_ratio': '--'},
 {'name': 'Applied Optoelectronics, Inc.',
  'symbol': 'AAOI',
  'price': '112.15',
  'change': '+8.24',
  'volume': '11.149M',
  'market_cap': '8.711B',
  'pe_ratio': '--'},
 {'name': 'Palantir Technologies Inc.',
  'symbol': 'PLTR',
  'price': '148.29',
  'change': '-0.17',
  'volume': '10.93M',
  'market_cap': '354.662B',
  'pe_ratio': '235.65'}]

In [21]:
len(data)

25

In [3]:
driver = webdriver.Chrome()
driver.maximize_window()

# explicit wait
wait = WebDriverWait(driver, 5)

# function to check if webpage is fully loaded
def wait_for_page_to_load(driver, wait, old_url=None):
    """
    Waits for the URL to change (if old_url is provided) and then 
    waits for the document.readyState to be complete.
    """
    # 1. If we are coming from another page, wait for the URL to actually change first
    if old_url:
        try:
            wait.until(EC.url_changes(old_url))
        except:
            print("The URL did not change within the timeout period.")

    # 2. Now wait for the new page to report 'complete' status
    try:
        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except:
        print(f"The page \"{driver.title}\" didn't fully load within the duration\n")
    else:
        # After the wait, driver.title and driver.current_url will be updated
        print(f"Successfully moved to: \"{driver.title}\"")
        print(f"Current URL: {driver.current_url}\n")
        
url = "https://finance.yahoo.com/"
driver.get(url)
wait_for_page_to_load(driver, wait)

# hovering on market menu
actions = ActionChains(driver)
market_menu = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/a[1]/div[1]"))
)
actions.move_to_element(market_menu).perform()

# find the stock element and click most_active
stocks_element = wait.until(
    EC.presence_of_element_located((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(stocks_element).perform()

most_active = wait.until(
    EC.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/nav[1]/ol[1]/li[3]/ol[1]/li[1]/ol[1]/li[1]/a[1]/span[1]"))
)
actions.move_to_element(most_active).perform()
most_active.click()

# wait_for_page_to_load(driver, wait)

wait_for_page_to_load(driver, wait, old_url = driver.current_url)

data = []
# scraping the data
while True:
    # scraping
    wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))
    rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    print(len(rows))

    for row in rows:
        values = row.find_elements(By.TAG_NAME, "td")
        # print([val.text for val in values])

        stock = {
            "name": values[1].text,
            "symbol": values[0].text,
            "price": values[3].text,
            "change": values[4].text,
            "volume": values[6].text,
            "market_cap": values[8].text,
            "pe_ratio": values[9].text
        }
        data.append(stock)
    # break
    # click next
    try:
        next_button = wait.until(
        EC.element_to_be_clickable((By.XPATH, '//*[@id="main-content-wrapper"]/section[1]/div/div[4]/div[3]/button[3]'))
        )
    except:
        print("The \"next\" button is not clickable. We have navigated through all the pages")
        break
    else:
        next_button.click()
        time.sleep(1)

# close the browser
driver.quit()

Successfully moved to: "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News"
Current URL: https://finance.yahoo.com/

Successfully moved to: "Most Active Stocks: US stocks with the highest trading volume today - Yahoo Finance"
Current URL: https://finance.yahoo.com/markets/stocks/most-active/

25
25
25
25
25
25
25
25
25
4
The "next" button is not clickable. We have navigated through all the pages

In [47]:
data

[{'name': 'NVIDIA Corporation',
  'symbol': 'NVDA',
  'price': '177.64',
  'change': '+0.25',
  'volume': '107.121M',
  'market_cap': '4.318T',
  'pe_ratio': '36.20'},
 {'name': 'Hologic, Inc.',
  'symbol': 'HOLX',
  'price': '76.01',
  'change': '+0.36',
  'volume': '101.956M',
  'market_cap': '16.969B',
  'pe_ratio': '31.48'},
 {'name': 'Plug Power Inc.',
  'symbol': 'PLUG',
  'price': '2.69',
  'change': '+0.28',
  'volume': '99.038M',
  'market_cap': '3.75B',
  'pe_ratio': '--'},
 {'name': 'Nokia Oyj',
  'symbol': 'NOK',
  'price': '8.89',
  'change': '+0.07',
  'volume': '83.6M',
  'market_cap': '49.629B',
  'pe_ratio': '66.82'},
 {'name': 'Soleno Therapeutics, Inc.',
  'symbol': 'SLNO',
  'price': '52.25',
  'change': '+12.76',
  'volume': '58.034M',
  'market_cap': '2.806B',
  'pe_ratio': '101.26'},
 {'name': 'Snap Inc.',
  'symbol': 'SNAP',
  'price': '4.71',
  'change': '+0.08',
  'volume': '52.134M',
  'market_cap': '7.955B',
  'pe_ratio': '--'},
 {'name': 'Intel Corporation',
  'symbol': 'INTC',
  'price': '50.32',
  'change': '-0.06',
  'volume': '49.049M',
  'market_cap': '252.648B',
  'pe_ratio': '--'},
 {'name': 'Ondas Inc.',
  'symbol': 'ONDS',
  'price': '9.52',
  'change': '-0.08',
  'volume': '45.278M',
  'market_cap': '4.586B',
  'pe_ratio': '--'},
 {'name': 'SoFi Technologies, Inc.',
  'symbol': 'SOFI',
  'price': '16.27',
  'change': '+0.42',
  'volume': '42.388M',
  'market_cap': '20.749B',
  'pe_ratio': '41.10'},
 {'name': 'Bitmine Immersion Technologies, Inc.',
  'symbol': 'BMNR',
  'price': '20.60',
  'change': '+1.15',
  'volume': '40.757M',
  'market_cap': '9.38B',
  'pe_ratio': '--'},
 {'name': 'MARA Holdings, Inc.',
  'symbol': 'MARA',
  'price': '8.85',
  'change': '+0.14',
  'volume': '36.387M',
  'market_cap': '3.365B',
  'pe_ratio': '--'},
 {'name': 'Tesla, Inc.',
  'symbol': 'TSLA',
  'price': '351.60',
  'change': '-9.12',
  'volume': '35.852M',
  'market_cap': '1.319T',
  'pe_ratio': '333.88'},
 {'name': 'Apple Inc.',
  'symbol': 'AAPL',
  'price': '258.86',
  'change': '+2.94',
  'volume': '29.32M',
  'market_cap': '3.805T',
  'pe_ratio': '32.46'},
 {'name': 'Baytex Energy Corp.',
  'symbol': 'BTE',
  'price': '4.40',
  'change': '+0.15',
  'volume': '28.182M',
  'market_cap': '3.382B',
  'pe_ratio': '--'},
 {'name': 'Pfizer Inc.',
  'symbol': 'PFE',
  'price': '27.83',
  'change': '-0.49',
  'volume': '25.128M',
  'market_cap': '158.307B',
  'pe_ratio': '20.82'},
 {'name': 'Palantir Technologies Inc.',
  'symbol': 'PLTR',
  'price': '147.93',
  'change': '-0.53',
  'volume': '25.114M',
  'market_cap': '353.801B',
  'pe_ratio': '235.65'},
 {'name': 'Venture Global, Inc.',
  'symbol': 'VG',
  'price': '15.94',
  'change': '+1.30',
  'volume': '24.911M',
  'market_cap': '39.164B',
  'pe_ratio': '17.02'},
 {'name': 'Nu Holdings Ltd.',
  'symbol': 'NU',
  'price': '14.26',
  'change': '+0.11',
  'volume': '24.847M',
  'market_cap': '69.242B',
  'pe_ratio': '24.20'},
 {'name': 'Archer Aviation Inc.',
  'symbol': 'ACHR',
  'price': '5.54',
  'change': '+0.12',
  'volume': '24.795M',
  'market_cap': '4.154B',
  'pe_ratio': '--'},
 {'name': 'Ford Motor Company',
  'symbol': 'F',
  'price': '11.61',
  'change': '+0.01',
  'volume': '24.344M',
  'market_cap': '46.569B',
  'pe_ratio': '--'},
 {'name': 'Robinhood Markets, Inc.',
  'symbol': 'HOOD',
  'price': '69.78',
  'change': '+0.88',
  'volume': '24.288M',
  'market_cap': '62.824B',
  'pe_ratio': '33.61'},
 {'name': 'Micron Technology, Inc.',
  'symbol': 'MU',
  'price': '379.20',
  'change': '+13.63',
  'volume': '23.354M',
  'market_cap': '427.637B',
  'pe_ratio': '17.23'},
 {'name': 'Rivian Automotive, Inc.',
  'symbol': 'RIVN',
  'price': '15.29',
  'change': '-0.11',
  'volume': '22.726M',
  'market_cap': '18.975B',
  'pe_ratio': '--'},
 {'name': 'Marvell Technology, Inc.',
  'symbol': 'MRVL',
  'price': '109.51',
  'change': '+2.40',
  'volume': '22.656M',
  'market_cap': '95.762B',
  'pe_ratio': '34.89'},
 {'name': 'Rocket Lab Corporation',
  'symbol': 'RKLB',
  'price': '67.67',
  'change': '-0.06',
  'volume': '22.284M',
  'market_cap': '38.532B',
  'pe_ratio': '--'},
 {'name': 'Warner Bros. Discovery, Inc.',
  'symbol': 'WBD',
  'price': '27.41',
  'change': '+0.09',
  'volume': '22.129M',
  'market_cap': '68.711B',
  'pe_ratio': '94.21'},
 {'name': 'Energy Transfer LP',
  'symbol': 'ET',
  'price': '18.96',
  'change': '+0.03',
  'volume': '22.015M',
  'market_cap': '65.228B',
  'pe_ratio': '15.65'},
 {'name': 'Stellantis N.V.',
  'symbol': 'STLA',
  'price': '7.48',
  'change': '-0.07',
  'volume': '21.866M',
  'market_cap': '21.673B',
  'pe_ratio': '--'},
 {'name': 'IREN Limited',
  'symbol': 'IREN',
  'price': '35.13',
  'change': '+0.36',
  'volume': '21.635M',
  'market_cap': '11.655B',
  'pe_ratio': '26.06'},
 {'name': 'Rocket Companies, Inc.',
  'symbol': 'RKT',
  'price': '15.03',
  'change': '+0.07',
  'volume': '21.51M',
  'market_cap': '42.382B',
  'pe_ratio': '--'},
 {'name': 'AXT, Inc.',
  'symbol': 'AXTI',
  'price': '41.99',
  'change': '-10.85',
  'volume': '21.162M',
  'market_cap': '2.334B',
  'pe_ratio': '--'},
 {'name': 'B2Gold Corp.',
  'symbol': 'BTG',
  'price': '4.64',
  'change': '-0.09',
  'volume': '20.609M',
  'market_cap': '6.233B',
  'pe_ratio': '17.07'},
 {'name': 'Netflix, Inc.',
  'symbol': 'NFLX',
  'price': '98.68',
  'change': '-0.44',
  'volume': '20.521M',
  'market_cap': '418.611B',
  'pe_ratio': '39.00'},
 {'name': 'Ambev S.A.',
  'symbol': 'ABEV',
  'price': '2.99',
  'change': '+0.06',
  'volume': '20.487M',
  'market_cap': '46.885B',
  'pe_ratio': '15.46'},
 {'name': 'Opendoor Technologies Inc.',
  'symbol': 'OPEN',
  'price': '4.61',
  'change': '-0.13',
  'volume': '19.956M',
  'market_cap': '4.418B',
  'pe_ratio': '--'},
 {'name': 'Comcast Corporation',
  'symbol': 'CMCSA',
  'price': '27.66',
  'change': '-0.27',
  'volume': '19.63M',
  'market_cap': '100.79B',
  'pe_ratio': '5.18'},
 {'name': 'Lloyds Banking Group plc',
  'symbol': 'LYG',
  'price': '5.24',
  'change': '+0.03',
  'volume': '19.533M',
  'market_cap': '94.403B',
  'pe_ratio': '14.19'},
 {'name': 'Hims & Hers Health, Inc.',
  'symbol': 'HIMS',
  'price': '20.33',
  'change': '+1.19',
  'volume': '19.5M',
  'market_cap': '4.634B',
  'pe_ratio': '37.36'},
 {'name': 'Norwegian Cruise Line Holdings Ltd.',
  'symbol': 'NCLH',
  'price': '19.37',
  'change': '+0.44',
  'volume': '18.404M',
  'market_cap': '8.824B',
  'pe_ratio': '20.69'},
 {'name': 'Intuitive Machines, Inc.',
  'symbol': 'LUNR',
  'price': '22.92',
  'change': '-1.07',
  'volume': '18.389M',
  'market_cap': '3.653B',
  'pe_ratio': '--'},
 {'name': 'Advanced Micro Devices, Inc.',
  'symbol': 'AMD',
  'price': '220.18',
  'change': '+2.68',
  'volume': '18.311M',
  'market_cap': '359.033B',
  'pe_ratio': '83.33'},
 {'name': 'American Airlines Group Inc.',
  'symbol': 'AAL',
  'price': '10.90',
  'change': '+0.06',
  'volume': '18.274M',
  'market_cap': '7.197B',
  'pe_ratio': '64.45'},
 {'name': 'Cipher Digital Inc.',
  'symbol': 'CIFR',
  'price': '13.35',
  'change': '+0.53',
  'volume': '18.112M',
  'market_cap': '5.408B',
  'pe_ratio': '--'},
 {'name': 'NuScale Power Corporation',
  'symbol': 'SMR',
  'price': '10.17',
  'change': '+0.02',
  'volume': '17.789M',
  'market_cap': '3.24B',
  'pe_ratio': '--'},
 {'name': 'Applied Digital Corporation',
  'symbol': 'APLD',
  'price': '25.19',
  'change': '+0.63',
  'volume': '17.774M',
  'market_cap': '7.043B',
  'pe_ratio': '--'},
 {'name': 'Gerdau S.A.',
  'symbol': 'GGB',
  'price': '3.76',
  'change': '-0.02',
  'volume': '17.752M',
  'market_cap': '7.433B',
  'pe_ratio': '28.75'},
 {'name': 'Grab Holdings Limited',
  'symbol': 'GRAB',
  'price': '3.56',
  'change': '-0.06',
  'volume': '17.604M',
  'market_cap': '14.618B',
  'pe_ratio': '60.33'},
 {'name': 'CleanSpark, Inc.',
  'symbol': 'CLSK',
  'price': '9.10',
  'change': '+0.31',
  'volume': '17.427M',
  'market_cap': '2.327B',
  'pe_ratio': '--'},
 {'name': 'Kenvue Inc.',
  'symbol': 'KVUE',
  'price': '17.30',
  'change': '+0.16',
  'volume': '17.022M',
  'market_cap': '33.159B',
  'pe_ratio': '22.55'},
 {'name': 'Applied Optoelectronics, Inc.',
  'symbol': 'AAOI',
  'price': '107.45',
  'change': '+3.54',
  'volume': '16.982M',
  'market_cap': '8.346B',
  'pe_ratio': '--'},
 {'name': 'CoreWeave, Inc.',
  'symbol': 'CRWV',
  'price': '80.94',
  'change': '-1.30',
  'volume': '16.933M',
  'market_cap': '42.549B',
  'pe_ratio': '--'},
 {'name': 'Alphabet Inc.',
  'symbol': 'GOOGL',
  'price': '299.99',
  'change': '+4.22',
  'volume': '16.933M',
  'market_cap': '3.629T',
  'pe_ratio': '27.38'},
 {'name': 'Huntington Bancshares Incorporated',
  'symbol': 'HBAN',
  'price': '15.94',
  'change': '+0.15',
  'volume': '16.538M',
  'market_cap': '32.472B',
  'pe_ratio': '11.36'},
 {'name': 'Exxon Mobil Corporation',
  'symbol': 'XOM',
  'price': '163.37',
  'change': '+2.68',
  'volume': '16.332M',
  'market_cap': '680.724B',
  'pe_ratio': '23.98'},
 {'name': 'Rigetti Computing, Inc.',
  'symbol': 'RGTI',
  'price': '14.20',
  'change': '+0.01',
  'volume': '15.98M',
  'market_cap': '4.717B',
  'pe_ratio': '--'},
 {'name': 'Coupang, Inc.',
  'symbol': 'CPNG',
  'price': '19.51',
  'change': '+0.56',
  'volume': '15.313M',
  'market_cap': '35.668B',
  'pe_ratio': '172.27'},
 {'name': 'UiPath, Inc.',
  'symbol': 'PATH',
  'price': '11.15',
  'change': '-0.09',
  'volume': '14.968M',
  'market_cap': '5.962B',
  'pe_ratio': '21.62'},
 {'name': 'KeyCorp',
  'symbol': 'KEY',
  'price': '20.66',
  'change': '+0.19',
  'volume': '14.666M',
  'market_cap': '22.512B',
  'pe_ratio': '13.47'},
 {'name': 'NIO Inc.',
  'symbol': 'NIO',
  'price': '6.24',
  'change': '+0.00',
  'volume': '14.529M',
  'market_cap': '15.779B',
  'pe_ratio': '--'},
 {'name': 'Denison Mines Corp.',
  'symbol': 'DNN',
  'price': '3.61',
  'change': '-0.07',
  'volume': '14.268M',
  'market_cap': '3.26B',
  'pe_ratio': '--'},
 {'name': 'D-Wave Quantum Inc.',
  'symbol': 'QBTS',
  'price': '14.14',
  'change': '-0.18',
  'volume': '14.216M',
  'market_cap': '5.231B',
  'pe_ratio': '--'},
 {'name': 'The Kraft Heinz Company',
  'symbol': 'KHC',
  'price': '23.57',
  'change': '+0.78',
  'volume': '14.194M',
  'market_cap': '27.901B',
  'pe_ratio': '--'},
 {'name': 'SoundHound AI, Inc.',
  'symbol': 'SOUN',
  'price': '6.70',
  'change': '-0.08',
  'volume': '14.189M',
  'market_cap': '2.833B',
  'pe_ratio': '--'},
 {'name': 'Pinterest, Inc.',
  'symbol': 'PINS',
  'price': '18.25',
  'change': '+0.07',
  'volume': '13.882M',
  'market_cap': '12.139B',
  'pe_ratio': '29.80'},
 {'name': 'Chipotle Mexican Grill, Inc.',
  'symbol': 'CMG',
  'price': '33.50',
  'change': '+0.34',
  'volume': '13.85M',
  'market_cap': '44.296B',
  'pe_ratio': '29.09'},
 {'name': 'HP Inc.',
  'symbol': 'HPQ',
  'price': '18.94',
  'change': '-0.57',
  'volume': '13.343M',
  'market_cap': '17.387B',
  'pe_ratio': '7.38'},
 {'name': 'Citigroup Inc.',
  'symbol': 'C',
  'price': '117.36',
  'change': '+2.11',
  'volume': '13.315M',
  'market_cap': '295.348B',
  'pe_ratio': '16.48'},
 {'name': 'ImmunityBio, Inc.',
  'symbol': 'IBRX',
  'price': '7.08',
  'change': '-0.22',
  'volume': '13.289M',
  'market_cap': '7.312B',
  'pe_ratio': '--'},
 {'name': 'AGNC Investment Corp.',
  'symbol': 'AGNC',
  'price': '10.20',
  'change': '+0.05',
  'volume': '13.164M',
  'market_cap': '11.457B',
  'pe_ratio': '6.90'},
 {'name': 'AST SpaceMobile, Inc.',
  'symbol': 'ASTS',
  'price': '94.81',
  'change': '+2.19',
  'volume': '13.143M',
  'market_cap': '36.22B',
  'pe_ratio': '--'},
 {'name': 'Compass, Inc.',
  'symbol': 'COMP',
  'price': '6.80',
  'change': '-0.27',
  'volume': '12.88M',
  'market_cap': '5.047B',
  'pe_ratio': '--'},
 {'name': 'First Majestic Silver Corp.',
  'symbol': 'AG',
  'price': '21.40',
  'change': '-0.44',
  'volume': '12.873M',
  'market_cap': '10.553B',
  'pe_ratio': '64.32'},
 {'name': 'Itaú Unibanco Holding S.A.',
  'symbol': 'ITUB',
  'price': '8.43',
  'change': '+0.09',
  'volume': '12.713M',
  'market_cap': '92.909B',
  'pe_ratio': '10.80'},
 {'name': 'Sandisk Corporation',
  'symbol': 'SNDK',
  'price': '724.63',
  'change': '+23.04',
  'volume': '12.708M',
  'market_cap': '106.956B',
  'pe_ratio': '--'},
 {'name': 'Aurora Innovation, Inc.',
  'symbol': 'AUR',
  'price': '4.20',
  'change': '+0.05',
  'volume': '12.613M',
  'market_cap': '8.185B',
  'pe_ratio': '--'},
 {'name': 'Oracle Corporation',
  'symbol': 'ORCL',
  'price': '145.54',
  'change': '-0.84',
  'volume': '12.53M',
  'market_cap': '418.58B',
  'pe_ratio': '26.27'},
 {'name': 'Fermi Inc.',
  'symbol': 'FRMI',
  'price': '5.13',
  'change': '-0.22',
  'volume': '12.057M',
  'market_cap': '3.15B',
  'pe_ratio': '--'},
 {'name': 'Broadcom Inc.',
  'symbol': 'AVGO',
  'price': '314.43',
  'change': '-0.12',
  'volume': '12.051M',
  'market_cap': '1.491T',
  'pe_ratio': '61.30'},
 {'name': 'Corning Incorporated',
  'symbol': 'GLW',
  'price': '146.50',
  'change': '-1.42',
  'volume': '11.929M',
  'market_cap': '125.846B',
  'pe_ratio': '80.83'},
 {'name': 'Halliburton Company',
  'symbol': 'HAL',
  'price': '37.82',
  'change': '-0.35',
  'volume': '11.809M',
  'market_cap': '31.676B',
  'pe_ratio': '25.45'},
 {'name': 'NIKE, Inc.',
  'symbol': 'NKE',
  'price': '44.06',
  'change': '-0.18',
  'volume': '11.782M',
  'market_cap': '65.233B',
  'pe_ratio': '29.13'},
 {'name': 'IonQ, Inc.',
  'symbol': 'IONQ',
  'price': '29.24',
  'change': '-0.06',
  'volume': '11.732M',
  'market_cap': '10.751B',
  'pe_ratio': '--'},
 {'name': 'Cenovus Energy Inc.',
  'symbol': 'CVE',
  'price': '26.88',
  'change': '+0.32',
  'volume': '11.721M',
  'market_cap': '50.713B',
  'pe_ratio': '17.17'},
 {'name': 'Banco Bradesco S.A.',
  'symbol': 'BBD',
  'price': '3.72',
  'change': '+0.06',
  'volume': '11.589M',
  'market_cap': '39.528B',
  'pe_ratio': '8.54'},
 {'name': 'Novo Nordisk A/S',
  'symbol': 'NVO',
  'price': '36.67',
  'change': '-0.31',
  'volume': '11.504M',
  'market_cap': '162.758B',
  'pe_ratio': '10.29'},
 {'name': 'CNH Industrial N.V.',
  'symbol': 'CNH',
  'price': '10.73',
  'change': '+0.08',
  'volume': '11.46M',
  'market_cap': '13.315B',
  'pe_ratio': '26.06'},
 {'name': 'Cleveland-Cliffs Inc.',
  'symbol': 'CLF',
  'price': '8.53',
  'change': '+0.13',
  'volume': '11.299M',
  'market_cap': '4.865B',
  'pe_ratio': '--'},
 {'name': 'Boston Scientific Corporation',
  'symbol': 'BSX',
  'price': '62.59',
  'change': '-0.23',
  'volume': '11.19M',
  'market_cap': '93.02B',
  'pe_ratio': '32.38'},
 {'name': 'Invesco Ltd.',
  'symbol': 'IVZ',
  'price': '22.88',
  'change': '-1.26',
  'volume': '11.085M',
  'market_cap': '10.166B',
  'pe_ratio': '--'},
 {'name': 'PayPal Holdings, Inc.',
  'symbol': 'PYPL',
  'price': '45.48',
  'change': '+0.14',
  'volume': '11.004M',
  'market_cap': '42.553B',
  'pe_ratio': '8.38'},
 {'name': 'Conagra Brands, Inc.',
  'symbol': 'CAG',
  'price': '15.78',
  'change': '+0.06',
  'volume': '10.985M',
  'market_cap': '7.55B',
  'pe_ratio': '--'},
 {'name': 'Blue Owl Capital Inc.',
  'symbol': 'OWL',
  'price': '8.45',
  'change': '-0.12',
  'volume': '10.984M',
  'market_cap': '13.185B',
  'pe_ratio': '83.01'},
 {'name': 'The Charles Schwab Corporation',
  'symbol': 'SCHW',
  'price': '92.99',
  'change': '-0.78',
  'volume': '10.967M',
  'market_cap': '165.237B',
  'pe_ratio': '20.17'},
 {'name': 'Nebius Group N.V.',
  'symbol': 'NBIS',
  'price': '112.54',
  'change': '+3.72',
  'volume': '10.908M',
  'market_cap': '28.475B',
  'pe_ratio': '949.43'},
 {'name': 'Walmart Inc.',
  'symbol': 'WMT',
  'price': '126.79',
  'change': '+1.00',
  'volume': '10.848M',
  'market_cap': '1.011T',
  'pe_ratio': '39.43'},
 {'name': 'Hewlett Packard Enterprise Company',
  'symbol': 'HPE',
  'price': '24.58',
  'change': '-0.03',
  'volume': '10.816M',
  'market_cap': '32.662B',
  'pe_ratio': '--'},
 {'name': 'Unity Software Inc.',
  'symbol': 'U',
  'price': '21.99',
  'change': '-0.76',
  'volume': '10.706M',
  'market_cap': '9.595B',
  'pe_ratio': '--'},
 {'name': 'Paramount Skydance Corporation',
  'symbol': 'PSKY',
  'price': '9.85',
  'change': '+0.33',
  'volume': '10.659M',
  'market_cap': '10.951B',
  'pe_ratio': '--'},
 {'name': 'Keurig Dr Pepper Inc.',
  'symbol': 'KDP',
  'price': '25.70',
  'change': '+0.39',
  'volume': '10.558M',
  'market_cap': '34.918B',
  'pe_ratio': '16.54'},
 {'name': 'Permian Resources Corporation',
  'symbol': 'PR',
  'price': '21.13',
  'change': '-0.05',
  'volume': '10.472M',
  'market_cap': '17.907B',
  'pe_ratio': '16.56'},
 {'name': 'Fastly, Inc.',
  'symbol': 'FSLY',
  'price': '31.54',
  'change': '-1.96',
  'volume': '10.344M',
  'market_cap': '4.788B',
  'pe_ratio': '--'},
 {'name': 'Copart, Inc.',
  'symbol': 'CPRT',
  'price': '32.84',
  'change': '-0.56',
  'volume': '10.206M',
  'market_cap': '31.79B',
  'pe_ratio': '21.01'},
 {'name': 'STMicroelectronics N.V.',
  'symbol': 'STM',
  'price': '35.44',
  'change': '+1.12',
  'volume': '10.198M',
  'market_cap': '31.498B',
  'pe_ratio': '185.59'},
 {'name': 'Hecla Mining Company',
  'symbol': 'HL',
  'price': '19.12',
  'change': '-0.06',
  'volume': '10.152M',
  'market_cap': '12.817B',
  'pe_ratio': '39.14'},
 {'name': 'Firefly Aerospace Inc.',
  'symbol': 'FLY',
  'price': '34.85',
  'change': '+1.92',
  'volume': '10.042M',
  'market_cap': '5.574B',
  'pe_ratio': '--'},
 {'name': 'Lyft, Inc.',
  'symbol': 'LYFT',
  'price': '13.70',
  'change': '+0.36',
  'volume': '10.004M',
  'market_cap': '5.471B',
  'pe_ratio': '1.93'},
 {'name': 'Bank of America Corporation',
  'symbol': 'BAC',
  'price': '50.06',
  'change': '+0.51',
  'volume': '9.989M',
  'market_cap': '359.265B',
  'pe_ratio': '12.96'},
 {'name': 'Super Micro Computer, Inc.',
  'symbol': 'SMCI',
  'price': '22.31',
  'change': '-0.65',
  'volume': '9.723M',
  'market_cap': '13.394B',
  'pe_ratio': '16.95'},
 {'name': 'Fortuna Mining Corp.',
  'symbol': 'FSM',
  'price': '10.27',
  'change': '0.00',
  'volume': '9.691M',
  'market_cap': '3.162B',
  'pe_ratio': '12.30'},
 {'name': 'Amazon.com, Inc.',
  'symbol': 'AMZN',
  'price': '212.46',
  'change': '+2.69',
  'volume': '9.575M',
  'market_cap': '2.281T',
  'pe_ratio': '29.26'},
 {'name': 'The Bank of Nova Scotia',
  'symbol': 'BNS',
  'price': '70.27',
  'change': '+0.15',
  'volume': '9.543M',
  'market_cap': '86.746B',
  'pe_ratio': '14.48'},
 {'name': 'Navitas Semiconductor Corporation',
  'symbol': 'NVTS',
  'price': '8.84',
  'change': '+0.03',
  'volume': '9.495M',
  'market_cap': '2.039B',
  'pe_ratio': '--'},
 {'name': 'Meta Platforms, Inc.',
  'symbol': 'META',
  'price': '573.02',
  'change': '-1.44',
  'volume': '9.483M',
  'market_cap': '1.449T',
  'pe_ratio': '24.46'},
 {'name': 'Devon Energy Corporation',
  'symbol': 'DVN',
  'price': '49.65',
  'change': '+0.16',
  'volume': '9.358M',
  'market_cap': '30.855B',
  'pe_ratio': '11.87'},
 {'name': 'Lumen Technologies, Inc.',
  'symbol': 'LUMN',
  'price': '6.63',
  'change': '-0.36',
  'volume': '9.335M',
  'market_cap': '6.8B',
  'pe_ratio': '--'},
 {'name': 'Transocean Ltd.',
  'symbol': 'RIG',
  'price': '6.59',
  'change': '0.00',
  'volume': '9.188M',
  'market_cap': '7.293B',
  'pe_ratio': '--'},
 {'name': 'Lucid Group, Inc.',
  'symbol': 'LCID',
  'price': '9.33',
  'change': '-0.63',
  'volume': '9.136M',
  'market_cap': '3.057B',
  'pe_ratio': '--'},
 {'name': 'ServiceNow, Inc.',
  'symbol': 'NOW',
  'price': '102.42',
  'change': '+0.42',
  'volume': '9.134M',
  'market_cap': '108.068B',
  'pe_ratio': '61.08'},
 {'name': 'Salesforce, Inc.',
  'symbol': 'CRM',
  'price': '185.03',
  'change': '-2.15',
  'volume': '8.888M',
  'market_cap': '173.373B',
  'pe_ratio': '24.00'},
 {'name': 'Truist Financial Corporation',
  'symbol': 'TFC',
  'price': '47.64',
  'change': '+0.48',
  'volume': '8.677M',
  'market_cap': '60.943B',
  'pe_ratio': '12.35'},
 {'name': 'Viatris Inc.',
  'symbol': 'VTRS',
  'price': '13.41',

In [48]:
len(data)

229

# Cleaning the data

In [49]:
stocks_df = (
    pd
    .DataFrame(data)
)

stocks_df

,name,symbol,price,change,volume,market_cap,pe_ratio
0,NVIDIA Corporation,NVDA,177.64,+0.25,107.121M,4.318T,36.20
1,"Hologic, Inc.",HOLX,76.01,+0.36,101.956M,16.969B,31.48
2,Plug Power Inc.,PLUG,2.69,+0.28,99.038M,3.75B,--
3,Nokia Oyj,NOK,8.89,+0.07,83.6M,49.629B,66.82
4,"Soleno Therapeutics, Inc.",SLNO,52.25,+12.76,58.034M,2.806B,101.26
...,...,...,...,...,...,...,...
224,"JD.com, Inc.",JD,28.51,+0.05,5.106M,41.245B,15.20
225,"QXO, Inc.",QXO,19.02,-0.01,5.088M,13.752B,--
226,General Motors Company,GM,73.43,+0.89,5.062M,68.5B,16.98
227,GE Aerospace,GE,288.69,+7.53,5.061M,304.514B,42.80
228,FS KKR Capital Corp.,FSK,10.73,+0.22,5.043M,3.005B,267.59

In [7]:
stocks_df = (
    pd
    .DataFrame(data)
    .dtypes
)

stocks_df

name          str
symbol        str
price         str
change        str
volume        str
market_cap    str
pe_ratio      str
dtype: object

In [8]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
)

stocks_df

,name,symbol,price,change,volume,market_cap,pe_ratio
0,NVIDIA Corporation,NVDA,177.64,+0.25,107.121M,4.318T,36.20
1,"Hologic, Inc.",HOLX,76.01,+0.36,101.956M,16.969B,31.48
2,Plug Power Inc.,PLUG,2.69,+0.28,99.038M,3.75B,--
3,Nokia Oyj,NOK,8.89,+0.07,83.6M,49.629B,66.82
4,"Soleno Therapeutics, Inc.",SLNO,52.25,+12.76,58.034M,2.806B,101.26
...,...,...,...,...,...,...,...
224,"JD.com, Inc.",JD,28.51,+0.05,5.106M,41.245B,15.20
225,"QXO, Inc.",QXO,19.02,-0.01,5.088M,13.752B,--
226,General Motors Company,GM,73.43,+0.89,5.062M,68.5B,16.98
227,GE Aerospace,GE,288.69,+7.53,5.061M,304.514B,42.80
228,FS KKR Capital Corp.,FSK,10.73,+0.22,5.043M,3.005B,267.59

In [9]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    # .symbol.unique()
    # .name.unique()
    # .price
    .rename(columns = {
            "price": "price_usd"
        }
    )
)

# print(stocks_df)
stocks_df

,name,symbol,price_usd,change,volume,market_cap,pe_ratio
0,NVIDIA Corporation,NVDA,177.64,+0.25,107.121M,4.318T,36.20
1,"Hologic, Inc.",HOLX,76.01,+0.36,101.956M,16.969B,31.48
2,Plug Power Inc.,PLUG,2.69,+0.28,99.038M,3.75B,--
3,Nokia Oyj,NOK,8.89,+0.07,83.6M,49.629B,66.82
4,"Soleno Therapeutics, Inc.",SLNO,52.25,+12.76,58.034M,2.806B,101.26
...,...,...,...,...,...,...,...
224,"JD.com, Inc.",JD,28.51,+0.05,5.106M,41.245B,15.20
225,"QXO, Inc.",QXO,19.02,-0.01,5.088M,13.752B,--
226,General Motors Company,GM,73.43,+0.89,5.062M,68.5B,16.98
227,GE Aerospace,GE,288.69,+7.53,5.061M,304.514B,42.80
228,FS KKR Capital Corp.,FSK,10.73,+0.22,5.043M,3.005B,267.59

In [10]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    # .symbol.unique()
    # .name.unique()
    .price.str.extract(r"([^0-9.])")
    # .rename(columns = {
    #         "price": "price_usd"
    #     }
    # )
)

# print(stocks_df)
stocks_df

       0
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
..   ...
224  NaN
225  NaN
226  NaN
227  NaN
228  NaN

[229 rows x 1 columns]

In [11]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    # .symbol.unique()
    # .name.unique()
    .price.str.extract(r"([^0-9.])", expand = False).unique()
    # .rename(columns = {
    #         "price": "price_usd"
    #     }
    # )
    
)

# print(stocks_df)
stocks_df

<StringArray>
[nan]
Length: 1, dtype: str

In [12]:
# stocks_df['price'] = stocks_df['price'].astype('float')
# It is not considered good practice
# Using assign is the go-to method to update any column in place

stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    # .symbol.unique()
    # .name.unique()
    # .price.str.extract(r"([^0-9.])", expand = False).unique()
    # .rename(columns = {
    #         "price": "price_usd"
    #     }
    # )
    .assign(
        price = lambda df_: pd.to_numeric(df_.price)
    )
    
)

# print(stocks_df)
stocks_df.dtypes

name              str
symbol            str
price         float64
change            str
volume            str
market_cap        str
pe_ratio          str
dtype: object

In [21]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price)
    )
    .rename(columns = {
            "price": "price_usd"
        }
    )
    
)

# print(stocks_df)
stocks_df.change.str.extract(r"([^0-9.])", expand = False).unique()

<StringArray>
['+', '-', nan]
Length: 3, dtype: str

In [22]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: df_.change.str.replace("+", "")
    )
    .rename(columns = {
            "price": "price_usd"
        }
    )
    
)

# print(stocks_df)
stocks_df.change.str.extract(r"([^0-9.])", expand = False).unique()

<StringArray>
[nan, '-']
Length: 2, dtype: str

In [23]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: df_.change.str.replace("+", "")
    )
    .rename(columns = {
            "price": "price_usd"
        }
    )
    
)

# print(stocks_df)
stocks_df.change.unique()

<StringArray>
[ '0.25',  '0.36',  '0.28',  '0.07', '12.76',  '0.08', '-0.06', '-0.08',
  '0.42',  '1.15',
 ...
  '1.62',  '1.23', '-0.81',  '0.54', '-0.69',  '0.79', '-0.25',  '2.30',
  '0.89',  '7.53']
Length: 141, dtype: str

In [24]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: pd.to_numeric(df_.change.str.replace("+", ""))
    )
    .rename(columns = {
            "price": "price_usd"
        }
    )
    
)

# stocks_df.dtypes
stocks_df

,name,symbol,price_usd,change,volume,market_cap,pe_ratio
0,NVIDIA Corporation,NVDA,177.64,0.25,107.121M,4.318T,36.20
1,"Hologic, Inc.",HOLX,76.01,0.36,101.956M,16.969B,31.48
2,Plug Power Inc.,PLUG,2.69,0.28,99.038M,3.75B,--
3,Nokia Oyj,NOK,8.89,0.07,83.6M,49.629B,66.82
4,"Soleno Therapeutics, Inc.",SLNO,52.25,12.76,58.034M,2.806B,101.26
...,...,...,...,...,...,...,...
224,"JD.com, Inc.",JD,28.51,0.05,5.106M,41.245B,15.20
225,"QXO, Inc.",QXO,19.02,-0.01,5.088M,13.752B,--
226,General Motors Company,GM,73.43,0.89,5.062M,68.5B,16.98
227,GE Aerospace,GE,288.69,7.53,5.061M,304.514B,42.80
228,FS KKR Capital Corp.,FSK,10.73,0.22,5.043M,3.005B,267.59

In [25]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: pd.to_numeric(df_.change.str.replace("+", ""))
    )
    .rename(columns = {
            "price": "price_usd"
        }
    )
    
)


# print(stocks_df)
stocks_df.volume.str.extract(r"([^0-9.])", expand = False).unique()

<StringArray>
['M']
Length: 1, dtype: str

In [28]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: pd.to_numeric(df_.change.str.replace("+", "")),
        volume = lambda df_: pd.to_numeric(df_.volume.str.replace("M", ""))
    )
    .rename(columns = {
            "price": "price_usd",
            "volume": "volume_M"
        }
    )
    
)


# stocks_df
stocks_df.dtypes

name              str
symbol            str
price_usd     float64
change        float64
volume_M      float64
market_cap        str
pe_ratio          str
dtype: object

In [30]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: pd.to_numeric(df_.change.str.replace("+", "")),
        volume = lambda df_: pd.to_numeric(df_.volume.str.replace("M", ""))
    )
    .rename(columns = {
            "price": "price_usd",
            "volume": "volume_M"
        }
    )
    
)


# stocks_df
stocks_df.market_cap.str.extract(r"([^0-9.])", expand = False).unique()

<StringArray>
['T', 'B']
Length: 2, dtype: str

In [34]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: pd.to_numeric(df_.change.str.replace("+", "")),
        volume = lambda df_: pd.to_numeric(df_.volume.str.replace("M", "")),
        market_cap = lambda df_: df_.market_cap.apply(lambda val: float(val.replace("B", "")) if ("B" in val) else float(val.replace("T", "")) * 1000)
    )
    .rename(columns = {
            "price": "price_usd",
            "volume": "volume_M",
            "market_cap": "market_cap_B"
        }
    )
    
)


# stocks_df
stocks_df.dtypes

name                str
symbol              str
price_usd       float64
change          float64
volume_M        float64
market_cap_B    float64
pe_ratio            str
dtype: object

In [50]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: pd.to_numeric(df_.change.str.replace("+", "")),
        volume = lambda df_: pd.to_numeric(df_.volume.str.replace("M", "")),
        market_cap = lambda df_: df_.market_cap.apply(lambda val: float(val.replace("B", "")) if ("B" in val) else float(val.replace("T", "")) * 1000)
    )
    .rename(columns = {
            "price": "price_usd",
            "volume": "volume_M",
            "market_cap": "market_cap_B"
        }
    )
    
)


stocks_df.pe_ratio.str.extract(r"([^0-9.])", expand = False).unique()

<StringArray>
[nan, '-', ',']
Length: 3, dtype: str

In [56]:
list(stocks_df.pe_ratio.values)

['36.20',
 '31.48',
 '--',
 '66.82',
 '101.26',
 '--',
 '--',
 '--',
 '41.10',
 '--',
 '--',
 '333.88',
 '32.46',
 '--',
 '20.82',
 '235.65',
 '17.02',
 '24.20',
 '--',
 '--',
 '33.61',
 '17.23',
 '--',
 '34.89',
 '--',
 '94.21',
 '15.65',
 '--',
 '26.06',
 '--',
 '--',
 '17.07',
 '39.00',
 '15.46',
 '--',
 '5.18',
 '14.19',
 '37.36',
 '20.69',
 '--',
 '83.33',
 '64.45',
 '--',
 '--',
 '--',
 '28.75',
 '60.33',
 '--',
 '22.55',
 '--',
 '--',
 '27.38',
 '11.36',
 '23.98',
 '--',
 '172.27',
 '21.62',
 '13.47',
 '--',
 '--',
 '--',
 '--',
 '--',
 '29.80',
 '29.09',
 '7.38',
 '16.48',
 '--',
 '6.90',
 '--',
 '--',
 '64.32',
 '10.80',
 '--',
 '--',
 '26.27',
 '--',
 '61.30',
 '80.83',
 '25.45',
 '29.13',
 '--',
 '17.17',
 '8.54',
 '10.29',
 '26.06',
 '--',
 '32.38',
 '--',
 '8.38',
 '--',
 '83.01',
 '20.17',
 '949.43',
 '39.43',
 '--',
 '--',
 '--',
 '16.54',
 '16.56',
 '--',
 '21.01',
 '185.59',
 '39.14',
 '--',
 '1.93',
 '12.96',
 '16.95',
 '12.30',
 '29.26',
 '14.48',
 '--',
 '24.46',
 '11.87',
 '--',
 '--',
 '--',
 '61.08',
 '24.00',
 '12.35',
 '--',
 '--',
 '14.26',
 '27.58',
 '40.38',
 '--',
 '25.24',
 '--',
 '30.01',
 '15.44',
 '27.02',
 '8.72',
 '--',
 '12.82',
 '--',
 '24.11',
 '9.68',
 '17.23',
 '--',
 '15.20',
 '21.04',
 '--',
 '51.67',
 '10.81',
 '20.09',
 '9.19',
 '25.87',
 '11.97',
 '13.35',
 '10.54',
 '10.92',
 '17.40',
 '23.37',
 '2,302.10',
 '38.18',
 '24.84',
 '14.72',
 '27.65',
 '38.55',
 '11.49',
 '15.53',
 '9.29',
 '--',
 '135.96',
 '20.96',
 '--',
 '21.21',
 '78.43',
 '11.55',
 '--',
 '5.64',
 '--',
 '7.68',
 '5.97',
 '9,599.36',
 '--',
 '--',
 '19.17',
 '7.93',
 '19.48',
 '--',
 '--',
 '--',
 '10.60',
 '234.39',
 '--',
 '--',
 '--',
 '8.01',
 '--',
 '30.44',
 '27.32',
 '16.60',
 '27.05',
 '14.22',
 '--',
 '21.66',
 '252.77',
 '--',
 '77.16',
 '16.17',
 '9.73',
 '7.45',
 '43.11',
 '--',
 '--',
 '30.95',
 '18.07',
 '28.25',
 '--',
 '2,378.83',
 '16.19',
 '--',
 '--',
 '--',
 '214.45',
 '11.36',
 '--',
 '--',
 '15.98',
 '12.17',
 '9.66',
 '93.12',
 '7.32',
 '15.20',
 '--',
 '16.98',
 '42.80',
 '267.59']

In [58]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: pd.to_numeric(df_.change.str.replace("+", "")),
        volume = lambda df_: pd.to_numeric(df_.volume.str.replace("M", "")),
        market_cap = lambda df_: df_.market_cap.apply(lambda val: float(val.replace("B", "")) if ("B" in val) else float(val.replace("T", "")) * 1000),
        pe_ratio = lambda df_: (
            df_
            .pe_ratio
            .replace("--", np.nan)
            .str.replace(",", "")
        )
    )
    .rename(columns = {
            "price": "price_usd",
            "volume": "volume_M",
            "market_cap": "market_cap_B"
        }
    )
    
)

# stocks_df.pe_ratio
stocks_df.pe_ratio.str.extract(r"([^0-9.])", expand = False).unique()

<StringArray>
[nan]
Length: 1, dtype: str

In [60]:
stocks_df = (
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if (col.dtype == "str") else col)
    .assign(
        price = lambda df_: pd.to_numeric(df_.price),
        change = lambda df_: pd.to_numeric(df_.change.str.replace("+", "")),
        volume = lambda df_: pd.to_numeric(df_.volume.str.replace("M", "")),
        market_cap = lambda df_: df_.market_cap.apply(lambda val: float(val.replace("B", "")) if ("B" in val) else float(val.replace("T", "")) * 1000),
        pe_ratio = lambda df_: (
            df_
            .pe_ratio
            .replace("--", np.nan)
            .str.replace(",", "")
            .pipe(lambda col: pd.to_numeric(col))
        )
    )
    .rename(columns = {
            "price": "price_usd",
            "volume": "volume_M",
            "market_cap": "market_cap_B"
        }
    )
    
)

# stocks_df
stocks_df.dtypes

name                str
symbol              str
price_usd       float64
change          float64
volume_M        float64
market_cap_B    float64
pe_ratio        float64
dtype: object

In [64]:
import openpyxl
print(openpyxl.__version__)

ModuleNotFoundError: No module named 'openpyxl'

In [65]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [66]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [67]:
stocks_df.to_excel("yahoo-stocks-data.xlsx", index = False)